"""initial

Revision ID: 0001
Revises:
Create Date: 2026-10-08 12:45:59.398950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('routine_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_number')
    )
    op.create_table('body_weight_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_lb', sa.REAL(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('raw_label', sa.String(length=120), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('intensity', sa.String(length=8), nullable=False),
    sa.Column('illustration_key', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['routine_day.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('calories', sa.REAL(), nullable=True),
    sa.Column('protein_g', sa.REAL(), nullable=True),
    sa.Column('carbs_g', sa.REAL(), nullable=True),
    sa.Column('fat_g', sa.REAL(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('travel_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('pushups', sa.Integer(), nullable=True),
    sa.Column('situps', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.Column('travel_mode', sa.Boolean(), nullable=False),
    sa.Column('completed_pct', sa.REAL(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['routine_day.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planned_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('weight_lb', sa.REAL(), nullable=True),
    sa.Column('target_reps', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('travel_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('travel_session_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=True),
    sa.Column('movement', sa.String(length=10), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['travel_session_id'], ['travel_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('set_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('planned_set_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('set_number', sa.Integer(), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('actual_reps', sa.Integer(), nullable=True),
    sa.Column('actual_weight_lb', sa.REAL(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('is_pr', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['planned_set_id'], ['planned_set.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['workout_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'planned_set_id', name='uq_session_set')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('set_log')
    op.drop_table('travel_set')
    op.drop_table('planned_set')
    op.drop_table('workout_session')
    op.drop_table('travel_session')
    op.drop_table('meal_log')
    op.drop_table('exercise')
    op.drop_table('body_weight_log')
    op.drop_table('routine_day')
    op.drop_table('app_user')
    # ### end Alembic commands ###
